pipelineJob('db-update-job') {
  definition {
    cps {
      script('''
        pipeline {
          agent {
            kubernetes {
              yaml """
apiVersion: v1
kind: Pod
spec:
  containers:
    - name: postgres-client
      image: postgres:latest
      command:
        - cat
      tty: true
              """
            }
          }
          triggers {
            cron('*/5 * * * *')
          }
          stages {
            stage('Update Database') {
              steps {
                container('postgres-client') {
                  sh '''
                    echo "Testing connection..."
                    PGPASSWORD=postgrespass psql -h postgres-postgresql -U postgres -d postgresdb -c "SELECT 1 as test;"
                    
                    echo "Creating table if not exists..."
                    PGPASSWORD=postgrespass psql -h postgres-postgresql -U postgres -d postgresdb -c "CREATE TABLE IF NOT EXISTS timestamps (time TIMESTAMP);"
                    
                    echo "Inserting current timestamp..."
                    PGPASSWORD=postgrespass psql -h postgres-postgresql -U postgres -d postgresdb -c "INSERT INTO timestamps VALUES (NOW());"
                    
                    echo "Database operation completed"
                  '''
                }
              }
            }
          }
        }
      ''')
    }
  }
}
