apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jenkins-ingress
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`jenkins.local`)
      kind: Rule
      services:
        - name: jenkins
          port: 8080